- name: Check if nodes are deployed
  command: 'virsh list --name --all'
  register: all_vms

- debug: 
    msg: All VMs are ==> {{all_vms.stdout_lines}}

- name: deploying kube master node
  script: ./configs/master.sh
  when: '"kube-master" not in all_vms.stdout_lines'
  
- name: waiting for master node to deploy
  pause: 
    minutes: 2
  when: '"kube-master" not in all_vms.stdout_lines'

- name: deploying kube worker-0 node
  script: ./configs/worker0.sh        
  when: '"kube-worker0" not in all_vms.stdout_lines'
  
- name: waiting for worker-0 node to deploy
  pause: 
    minutes: 2
  when: '"kube-worker0" not in all_vms.stdout_lines'

- name: deploying kube worker-1  node
  script: ./configs/worker1.sh        
  when: '"kube-worker1" not in all_vms.stdout_lines'
  
- name: waiting for worker-1 node to deploy
  pause: 
    minutes: 5
  when: '"kube-worker1" not in all_vms.stdout_lines'

- name: Fetch all running domains
  command: 'virsh list --name --state-running'
  register: all_vms

- debug: 
    msg: All running VMs are ==> {{all_vms.stdout_lines}}

- name: starting nodes if not strted already
  command: virsh start {{ item }}
  ignore_errors: true
  with_items:
    - kube-master
    - kube-worker0
    - kube-worker1
  when: item not in all_vms.stdout_lines

- name: waiting for nodes to start
  pause: 
    sleep: 20
  when:
    - '"kube-master0" not in all_vms.stdout_lines'
    - '"kube-worker0" not in all_vms.stdout_lines'
    - '"kube-worker1" not in all_vms.stdout_lines'

