- hosts: localhost
  gather_facts: false
  ignore_errors: true  
  roles:
    -   deploy-vm  

- hosts: localhost
  gather_facts: false
  roles:
    -   prepare  

- hosts: masters
  gather_facts: false
  roles:
    -   master  
