- name: copying kubernetes.repo files
  copy:
    src: ./configs/kubernetes.repo
    dest: /etc/yum.repos.d/
    owner: root
    group: root
    mode: 0755

- name: adjust modprobe br_netfilter
  command: modprobe br_netfilter

- name: adjuts net bridge nf call iptables
  shell: "echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables"

- name: Letting iptables see bridged traffic
  copy:
    src: ./configs/k8s.conf
    dest: /etc/sysctl.d/k8s.conf
    owner: root
    group: root
    mode: 0755

- name: Reloading sysctl
  shell: "sysctl --system"

- name: Open up firewall ports
  firewalld:
      permanent: yes
      immediate: yes
      state: enabled
      port: "{{ item }}"
  with_items:
      - 30000-32767/tcp
      - 10250/tcp

- name: disable swap memory (1/2)
  command: swapoff -a

- name: Disable SWAP in fstab (2/2)
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s*swap\s+.*)$'
    replace: '# \1'

- name: Put SELinux in permissive mode, logging actions that would be blocked.
  selinux:
    policy: targeted
    state: permissive

- name: Create a systemd drop-in directory for the docker service
  file:
    path: /etc/systemd/system/docker.service.d
    owner: root
    group: root
    mode: 0755
    recurse: yes
    state: directory
  when: use_proxy == 'yes'

- name: Copy proxy files for docker daemon (1/2)
  template:
    src: http-proxy.j2
    dest: /etc/systemd/system/docker.service.d/http-proxy.conf
    mode: 0755
  when: use_proxy == 'yes'

- name: Copy proxy files for docker daemon (2/2)
  template:
    src: https-proxy.j2
    dest: /etc/systemd/system/docker.service.d/https-proxy.conf
    mode: 0755
  when: use_proxy == 'yes'

- name: Setting environment variables
  template:
    src: environment.j2
    dest: /etc/environment
    mode: 0755
  when: use_proxy == 'yes'

- name: Updating nameserver with organizational DNS server
  shell: echo "nameserver {{proxy_details.organizational_dns_server}}" >> /etc/resolv.conf
  when: use_proxy == 'yes'

- name: Install kubeadm and docker
  yum:
      name:
        - kubeadm
        - docker
      state: present

- name: Starting services
  service:
      name: "{{ item }}"
      enabled: yes
      state: started
  with_items:
      - kubelet
      - docker

- name: Check if this worker node is joined already
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: result

- debug: msg={{hostvars['DUMMY']['nodejn'][0]}}

- name: joining to the master
  shell: "{{hostvars['DUMMY']['nodejn'][0]}}"
  when: not result.stat.exists
